name: 'genomics_dwh'
version: '1.0.0'
profile: 'genomics_dwh'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  genomics_dwh:
    staging:
      +materialized: view
      +tags: ["bronze", "staging"]
    intermediate:
      +materialized: table
      +tags: ["silver", "intermediate"]
    marts:
      +materialized: table
      +tags: ["gold", "marts"]
      core:
        fct_variant_observation:
          +materialized: incremental
          +unique_key: ['sample_id_1kg', 'variant_key']
          +on_schema_change: 'append_new_columns'
        fct_mrd_test:
          +materialized: incremental
          +unique_key: 'test_sk'

