name: Deploy dbt Docs

on:
  push:
    branches:
      - main
    paths:
      - 'genomics_dwh/models/**'
      - 'genomics_dwh/macros/**'
      - 'genomics_dwh/dbt_project.yml'

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dbt and Dependencies
        run: |
          pip install dbt-duckdb dbt-utils
          dbt deps --project-dir ./genomics_dwh

      - name: Generate dbt Docs
        working-directory: ./genomics_dwh
        env:
          DBT_DUCKDB_PATH: "./ci_warehouse.duckdb"
        run: |
          dbt docs generate --profiles-dir .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./genomics_dwh/target
